### ISSUE TITLE
Backend failure

### ISSUE THREAD

**Issue by dxdc** [davidgiga1993/AudiAPI#11]
As of a few days ago, I see this message:

```
Exception: API error: invalid_request
Backend Failure
```

Is this no longer functional?

**Comment by wictorwilen** [comment]
Same issue here, cannot sign in.

```
HTTP/1.1 502 Bad Gateway
X-Auth-Error-Code: AB502
X-Auth-Error-Message: Backend Failure
X-FS-Tracking-ID: 00000000-0000-0000-0000-000000000000
X-FS-Error-Code: GW084
Content-Type: application/json;charset=utf-8
Content-Length: 79
Date: Mon, 16 Dec 2019 15:36:45 GMT
Connection: close
Server: www

{
  "error": "invalid_request",
  "error_description": "Backend Failure"
}
```

**Comment by VolkerMuehlhaus** [comment]
Same here since 12/12/2019.

There was a message in the Audi App that some new remote features/functions were added.  Maybe that change broke the access also.

**Comment by davidgiga1993** [comment]
According to the latest reviews of the app it seems like audi had quite a big outage.
Is this still an issue?

**Comment by dxdc** [comment]
> Is this still an issue? @davidgiga1993 

Yes, but not sure of the cause. Possibly they refactored their API?

**Comment by davidgiga1993** [comment]
I just took a look at the app again - luckily they included a lot of mock data definitions for all endpoints available and even source code for running a mock server. That explains the app size of 100mb 🙄 
Hopefully they didn't change too much

**Comment by andig** [comment]
> I just took a look at the app again 

@davidgiga1993 could you share how you're doing that? I'm still getting the backend errors and would like to take a stab at fixing plus adding more functionality around the charge endpoint.

**Comment by davidgiga1993** [comment]
Just use dex2jar or similar to unpack the apk. I've pushed the stub data to the `testing` branch

**Comment by andig** [comment]
> Just use dex2jar or similar to unpack the apk. 

Ah, Android? Not my territory ;)

> I've pushed the stub data to the testing branch

Thank you. I've done a quick check but couldn't find anything regarding the battery service?

Apart from that- would you by chance have any initial ideas regarding the `invalid_request` authorization error?

**Comment by davidgiga1993** [comment]
I see :) No not yet, I'll patch the app and use an MITM attack to get the correct request format. Hopefully by this week

**Comment by andig** [comment]
Very good. In case anybody wants to try I've followed the approach on iOS but am stuck at getting the proxy being accepted by iOS (https://github.com/mitmproxy/mitmproxy/issues/3748).

**Comment by davidgiga1993** [comment]
Yes the issue is that the app does ssl pinning with its own CAs so you need to modify the app in order for the MITM to work

**Comment by andig** [comment]
> Yes the issue is that the app does ssl pinning with its own CAs so you need to modify the app in order for the MITM to work

Can't do this on iOS unfortunately. Looking forward to your update :)

**Comment by andig** [comment]
Sorry for bothering you- any progress?

**Comment by VolkerMuehlhaus** [comment]
Do you still have that issue? I had that issue in December, but in the meantime David s code works again here, without modification.

**Comment by andig** [comment]
> I had that issue in December, but in the meantime David s code works again here, without modification.

Ah, sorry for the confusion! I didn't even try as the message here was that we'll need to update after investigating certificate ~~pinging~~ pinning. Working for me, seems this can be closed.

On a separate, ot, note: I'd need some help with the remote battery service. I'm a python noob and would like to decode the json into a proper python structure. Any help welcome.

**Comment by dxdc** [comment]
Just an update, everything working fine here as well! Must have been some kind of outage on their side?

**Comment by andig** [comment]
Seems this is fixed and can be closed ;)
