### ISSUE TITLE
API caching: Charge state delivers rounded values

### ISSUE THREAD

**Issue by andig** [davidgiga1993/AudiAPI#12]
For my EV charger [andig/evcc](https://github.com/andig/evcc) I'm polling the API to read battery charge state. It seems that- if polling regularly (5min interval), the API will only return rounded values, i.e. charge state will appear as 20, 25, 30, 35 etc...

Can anyone confirm this observation?

**Comment by VolkerMuehlhaus** [comment]
For my A3 e-tron PHEV I also get other values, but there seems to be some preference for 5% steps.

TimeStamp;Avg;
19.3.2020 16:36:00; **99**;
19.3.2020 15:06:00; **100**;
19.3.2020 14:36:00; **93**;
19.3.2020 14:06:00; **81**;
19.3.2020 13:36:00; **65**;
19.3.2020 13:06:00; **55**;
19.3.2020 12:36:00; **45**;
19.3.2020 10:36:00; **34**;
19.3.2020 10:06:00; **26**;
18.3.2020 15:06:00; **28**;

**Comment by andig** [comment]
Interesting. Must admit that I'm polling in shorter intervals while the car is connected (and hence I can't deplete the battery).

Btw (and please forgive me the OT response) here's how the charge power (blue) follows PV generation (yellow). Charge state values are only written in 30min interval unless they change to avoid a staircase pattern.

<img width="977" alt="Screenshot 2020-03-24 at 12 50 45" src="https://user-images.githubusercontent.com/184815/77422698-32ba9280-6dce-11ea-814f-c4f7fbfd746a.png">

**Comment by VolkerMuehlhaus** [comment]
Polling at slower rate is on purpose - I'm afraid that Audi will take measures to prevent ALL access if we abuse this API and thousands of users are polling so very frequently.

**Comment by andig** [comment]
I‘ve limited to 5min intervals. Would be happy to adjust if we can have a consensus/recommendation what a good value is?
