### ISSUE TITLE
Posting on PyPI

### ISSUE THREAD

**Issue by akhan69** [davidgiga1993/AudiAPI#3]
I am interested in using this library to integrate my Audi car with Home Assistant.  Home Assistant requires any dependencies to be available on PyPI.  Would you mind publishing there?  I am happy to publish it if you don't mind. Thanks.

**Comment by djmoonshine** [comment]
@akhan69 I'm actually trying out this library and have the same goal as you. How far have you gotten this far? I guess you still could use this in a custom component without this being on PyPI?

**Comment by akhan69** [comment]
@djmoonshine  I was able to get the car location by creating a platform and then a device tracker.  I haven't looked at it in a few months, got pulled off to work on something else.  I really wanted to get some of the other information such as milage and fuel levels, but I just haven't had the time to try and reverse engineer the services.

**Comment by djmoonshine** [comment]
@akhan69 Ok, then you have done a bit more work than me. Is the code available somewhere? If not, would you be willing to share it to me in some way?

**Comment by akhan69** [comment]
I haven't posted the code publicly yet.  I am happy to share it with you.  If you give me a couple of days I can post what I have on GitHub.

**Comment by djmoonshine** [comment]
@akhan69 Great! Thank you!

**Comment by davidgiga1993** [comment]
Sorry for the late reply. I'll soon upload the code as a Pypi package. Also I can provide you some sample code for getting the fuel data.

I'm also working on a soon to be released daemon which can put these data among others into a graphite DB for grafana visualization

**Comment by davidgiga1993** [comment]
Code is now available on PyPI
```
pip install audiapi 
```

Also here is some sample code to get the fuel level and milage:
```
def get_data():
    api = API()
    logon_service = LogonService(api)
    if not logon_service.restore_token():
        # We need to login
        with open('credentials.json') as data_file:
            data = json.load(data_file)
        logon_service.login(data['user'], data['pass'])

    car_service = CarService(api)
    vehicles_response = car_service.get_vehicles()
    data = {}
    for vehicle in vehicles_response.vehicles:
        if 'YOUR_VIN' != vehicle.vin:
            continue

        status_report_service = VehicleStatusReportService(api, vehicle)
        report = status_report_service.get_stored_vehicle_data()
        assert isinstance(report, VehicleDataResponse)
        for field in report.data_fields:
            if field.name == 'UTC_TIME_AND_KILOMETER_STATUS':
                data['kilometers'] = int(field.value)  # int in km
                continue
            if field.name == 'TEMPERATURE_OUTSIDE':
                data['temp.outsite'] = int(int(field.value) / 10 - 273)  # int in kelvin*10 (roughly)
                continue
            if field.name == 'TOTAL_RANGE':
                data['range.total'] = int(field.value)  # int in km
                continue
            if field.name == 'TANK_LEVEL_IN_PERCENTAGE':
                data['tankLevel'] = int(field.value)  # int in %
                continue
            if field.name == 'OIL_LEVEL_DIPSTICKS_PERCENTAGE':
                data['oilLevelPercent'] = float(field.value)  # in % float
                continue
            if field.name == 'ADBLUE_RANGE':
                data['range.adblue'] = int(field.value)  # int in km
                continue

        return data

    print('VIN not found')
    return None
```
