### ISSUE TITLE
Locking/unlocking

### ISSUE THREAD

**Issue by arjenvrh** [davidgiga1993/AudiAPI#6]
Hi David

Thanks for the great library. I was wondering where you got the information on the API to develop this library. I would like to extend it with locking/unlocking, but I'm having a hard time finding out the correct rest calls. Reverse engineering the myaudi calls with mitmproxy unfortunately was no success.

Regards
Arjen

**Comment by davidgiga1993** [comment]
There are multiple ways to do so:
- Decompile the app
- Swap the embedded root certificate of the apk with your own and use MITM-Proxy to capture the traffic of the app. Only importing the root CA into android won't work since the app does its own cert chain validation

**Comment by arjenvrh** [comment]
Unfortunately I only have access to an iOS device, making it hard to use mitmproxy. I glanced at the decompiled code, I don't think analysing it will be fun... ;-)

**Comment by davidgiga1993** [comment]
You can search for the `@Path` annotations, it should give you a hint in which files to look

**Comment by arjenvrh** [comment]
Well I've found all the relevant calls, but haven't been able how to add the secure pin needed for the locking/unlocking calls.

Anyway just to let you know in case you're interested: I've started integrating your library as an add-in to Home Assistant. 
See https://github.com/arjenvrh/audi_connect_ha
